After learning, practicing, and making article about overdetermined system of linear equation, 
it is always good that i do the same in python using popular library so i know my way around thing.

So here it is
### How to Solve Overdetermined System of Linear Equation in Python using NumPy

we're gonna use Normal Equation formula to find the best-fit solution of the overdetermined system.
![Normal equation formula](./images/image.png)

For more information, read my article:
[Guide on How To Find The Best-Fit Solutions in Linear Overdetermined System](https://medium.com/@MiloAillo/guide-on-how-to-find-the-best-fit-solutions-in-linear-overdetermined-system-614fb7e8dc47)

Now let us install and load NumPy to our project.

In [1]:
%pip install numpy

import numpy as np

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Now we need to have Coefficient Matrix and Constants Vector according to the Ax = b formula.
But no unknown variables here because the output is the unknown variable itself so i dont have to initialize anything here.

In [35]:
A = np.array([
    [8, 7],
    [1, 3],
    [4, 1]
])

b = np.array([
    [2],
    [7],
    [-15]
])

lets find the transposed of the Coefficient Matrix,

In [36]:
transposed_A = A.transpose()

print(transposed_A)

[[8 1 4]
 [7 3 1]]


lets multiply the the transposed A to A, like what the left-hand side of the formula show.

In [37]:
approximation_coefficient_matrix = np.matmul(transposed_A, A)

print(approximation_coefficient_matrix)

[[81 63]
 [63 59]]


now do the same with the right-hand side, tranposed A to b.

In [38]:
approximation_constants_vector = np.matmul(transposed_A, b)

print(approximation_constants_vector)

[[-37]
 [ 20]]


now we have the normal system of linear equation that holds the approximation solution to the previous overdetermined system.

to find the solution, we have to look at the formula,
#### Ax = b
we need to find the solution (x), so we need to remove the A.
normal algebraic form involve dividing both LHS and RHS value, but matrix is different. 
To remove a matrix, we need to multiply the matrix to the its inverse self.

but because this is a code, we can just ignore them and put the same inversed approximation coefficient matrix on the RHS, and that mean multiplying the approximation constants vector with it.

In [39]:
inversed_approximation_coefficient_matrix = np.linalg.inv(approximation_coefficient_matrix)

best_fit_solution = np.matmul(inversed_approximation_coefficient_matrix, approximation_constants_vector)

print(best_fit_solution)

[[-4.25061728]
 [ 4.87777778]]


yay we got our best-fit solution for our overdetermined system. Lets look at the graph to see if its correct,

![Graph Result](./images/result.png)

Yay, those point in the middle of all the intersection are the best-fit solution for our overdetermined system!